<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-3KOP925" failures="4" tests="5" name="Default test" time="115.919" errors="0" timestamp="2024-01-22T20:54:18 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="25.861">
    <failure type="java.lang.AssertionError" message="Failure got to catch block">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.RegistrationStepDef.the_user_clicks_on_register(RegistrationStepDef.java:122)
at ✽.the user clicks on register(file:///C:/Users/Sai/eclipse-workspace/RLL/Demo_Web_Shop/src/test/java/Features/Registration.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="24.449">
    <failure type="java.lang.AssertionError" message="Failure got to catch block">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.RegistrationStepDef.the_user_clicks_on_register(RegistrationStepDef.java:122)
at ✽.the user clicks on register(file:///C:/Users/Sai/eclipse-workspace/RLL/Demo_Web_Shop/src/test/java/Features/Registration.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="19.201">
    <failure type="java.lang.AssertionError" message="Failure got to catch block">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.RegistrationStepDef.the_user_clicks_on_register(RegistrationStepDef.java:122)
at ✽.the user clicks on register(file:///C:/Users/Sai/eclipse-workspace/RLL/Demo_Web_Shop/src/test/java/Features/Registration.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="21.474"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="19.27">
    <failure type="java.lang.AssertionError" message="Failure got to catch block">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.RegistrationStepDef.the_user_clicks_on_register(RegistrationStepDef.java:122)
at ✽.the user clicks on register(file:///C:/Users/Sai/eclipse-workspace/RLL/Demo_Web_Shop/src/test/java/Features/Registration.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
