<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-3KOP925" failures="4" tests="13" name="Runner.registration_testng_runner" time="252.756" errors="0" timestamp="2024-01-23T10:35:32 IST" skipped="8">
  <testcase classname="Runner.registration_testng_runner" name="runScenario" time="17.946">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.registration_testng_runner" name="runScenario" time="18.296">
    <failure message="Failure got to catch block" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.RegistrationStepDef.the_user_clicks_on_register(RegistrationStepDef.java:122)
at ✽.the user clicks on register(file:///C:/Users/Sai/eclipse-workspace/RLL/Demo_Web_Shop/src/test/java/Features/Registration.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.registration_testng_runner" name="runScenario" time="19.124">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.registration_testng_runner" name="runScenario" time="19.696">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.registration_testng_runner" name="runScenario" time="27.126">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.registration_testng_runner" name="runScenario" time="18.370"/>
  <system-out/>
  <testcase classname="Runner.registration_testng_runner" name="runScenario" time="18.605">
    <failure message="Failure got to catch block" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.RegistrationStepDef.the_user_clicks_on_register(RegistrationStepDef.java:122)
at ✽.the user clicks on register(file:///C:/Users/Sai/eclipse-workspace/RLL/Demo_Web_Shop/src/test/java/Features/Registration.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.registration_testng_runner" name="runScenario" time="18.018">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.registration_testng_runner" name="runScenario" time="19.582">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.registration_testng_runner" name="runScenario" time="18.993">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.registration_testng_runner" name="runScenario" time="18.691">
    <failure message="Failure got to catch block" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.RegistrationStepDef.the_user_clicks_on_register(RegistrationStepDef.java:122)
at ✽.the user clicks on register(file:///C:/Users/Sai/eclipse-workspace/RLL/Demo_Web_Shop/src/test/java/Features/Registration.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.registration_testng_runner" name="runScenario" time="19.518">
    <failure message="Failure got to catch block" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failure got to catch block
at org.testng.Assert.fail(Assert.java:110)
at Steps.RegistrationStepDef.the_user_clicks_on_register(RegistrationStepDef.java:122)
at ✽.the user clicks on register(file:///C:/Users/Sai/eclipse-workspace/RLL/Demo_Web_Shop/src/test/java/Features/Registration.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runner.registration_testng_runner" name="runScenario" time="18.791">
    <skipped/>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Runner.registration_testng_runner -->
